# Generated by Django 5.2.14 on 2026-05-27 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmissionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1 — Direct Emissions'), ('SCOPE_2', 'Scope 2 — Indirect (Electricity)'), ('SCOPE_3', 'Scope 3 — Value Chain')], max_length=20)),
                ('activity_type', models.CharField(choices=[('FUEL_COMBUSTION', 'Fuel Combustion'), ('ELECTRICITY_CONSUMPTION', 'Electricity Consumption'), ('BUSINESS_TRAVEL', 'Business Travel')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(max_length=20)),
                ('normalized_value_liters_or_kwh', models.FloatField()),
                ('calculated_co2e_kg', models.FloatField()),
                ('facility_code', models.CharField(blank=True, default='', help_text='WERKS / plant code from source system.', max_length=100)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('FLAGGED_ANOMALY', 'Flagged Anomaly'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('anomaly_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'normalized_emission_activity',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason_for_change', models.TextField()),
                ('changed_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='esg_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ingestion.normalizedemissionactivity')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='normalizedemissionactivity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_activities', to='ingestion.organization'),
        ),
        migrations.CreateModel(
            name='RawIngestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, default='', max_length=512)),
                ('raw_payload_snapshot', models.JSONField(default=dict)),
                ('processed_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='ingestion.organization')),
            ],
            options={
                'db_table': 'raw_ingestion_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='normalizedemissionactivity',
            name='raw_log',
            field=models.ForeignKey(help_text='Lineage pointer back to the raw ingestion event.', on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='ingestion.rawingestionlog'),
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP_EXPORT', 'SAP Export'), ('UTILITY_CSV', 'Utility Portal CSV'), ('CONCUR_JSON', 'Corporate Travel JSON')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_systems', to='ingestion.organization')),
            ],
            options={
                'db_table': 'source_system',
            },
        ),
        migrations.AddField(
            model_name='rawingestionlog',
            name='source_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_logs', to='ingestion.sourcesystem'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionactivity',
            index=models.Index(fields=['tenant', 'status'], name='normalized__tenant__26daa1_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionactivity',
            index=models.Index(fields=['tenant', 'scope_category'], name='normalized__tenant__56ebc5_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionactivity',
            index=models.Index(fields=['facility_code'], name='normalized__facilit_6a133c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcesystem',
            unique_together={('tenant', 'name')},
        ),
    ]
